### ISSUE TITLE
Translate to Korean

### ISSUE THREAD

**Issue by yohanhyunsungyi** [iwasrobbed/Swift-CheatSheet#24]
Hey there!
Thanks for the great cheat-sheet.
I would like to introduce these good works to Koreans.
Is there any chance that I can help translate it to Korean?

**Comment by iwasrobbed** [comment]
Always happy to have help! I'd be happy to link to a Korean version or include it in this repo as well @YohanHyunsungYi 🙌

**Comment by yohanhyunsungyi** [comment]
@iwasrobbed Great! I will start working and will make pull request. :)
