### ISSUE TITLE
PDF download

### ISSUE THREAD

**Issue by Abstract45** [iwasrobbed/Swift-CheatSheet#8]
When opening pdf download I get the error failed to load pdf on Google chrome Version 51.0.2704.63. I get the same error on safari as well.

**Comment by iwasrobbed** [comment]
Thanks for reporting @miwand ; Looks like GitPrint is having some issues for now https://github.com/adamburmister/gitprint.com/issues/50

**Comment by jgclark** [comment]
Issues still present today.
